#!/bin/bash
# Install Respond on scotch/box

# Download
echo "Downloading Respond..."
wget --content-disposition https://github.com/madoublet/respond/blob/master/dist/release.zip?raw=true

# Unzip
echo "Unzipping to /var/www"
unzip -o release.zip -d /var/www

# Create sites
echo "Creating sites and resources folders"
mkdir public/sites
mkdir resources/sites
chown -R www-data public/sites
chown -R www-data resources/sites
chown -R www-data storage

# Copy .env
cp .env.example .env

# Done
echo "done!"